---
title: "Project Modeling"
author: "Ethan Shen, Steven Herrera, Malavi Ravindran, Austin Jia"
date: "11/23/2019"
output: html_document
---

```{r}
library(tidyverse)
library(ggplot2)
require(caTools) 
```

```{r}
school_df_final <- read.csv("school_df_final.csv")
```



### Visualizations
```{r}
ggplot(data = final_school_data %>% filter(!is.na(region)), aes(x = percent_white)) + 
  geom_histogram() + 
  facet_wrap(~region)
```

```{r}
avg <- final_school_data %>%
  group_by(region) %>%
  mutate(mean_percent_white = mean(percent_white, na.rm=TRUE),
         mean_percent_male = mean(percent_male, na.rm=TRUE),
         mean_percent_eds = mean(percent_eds, na.rm=TRUE),
         mean_percent_swd = mean(percent_swd, na.rm=TRUE))
avg %>%
  distinct(region, mean_percent_white) %>%
  filter(!is.na(region)) %>%
  spread(region, mean_percent_white)
```

### Modeling 

```{r}
#splitting data into training and testing

set.seed(123)   #  set seed to ensure you always have same random numbers generated
rows <- sample(nrow(school_df_final))
school_df_final <- school_df_final[rows, ]
sample = sample.split(school_df_final,SplitRatio = 0.75) # splits the data in the ratio mentioned in SplitRatio. After splitting marks these rows as logical TRUE and the the remaining are marked as logical FALSE
training =subset(school_df_final,sample ==TRUE) # creates a training dataset named train1 with rows which are marked as TRUE
testing=subset(school_df_final, sample==FALSE)
train = na.omit(training)
test = na.omit(testing)
```


#### Regression

##### Linear
```{r}
# should we mean center percents? 
model1 = lm(data = final_school_data_imp, growth_index_score ~ .- growth_status - school_code - school_name)

summary(model1)


summary(final_school_data$growth_index_score)
```

##### Random Forest

```{r}
rf <- randomForest(
  growth_index_score ~ . -school_code - school_name - percent_ACTWR_meeting - percent_ACTSC_meeting - percent_ACTRD_meeting - percent_ACTMA_meeting - percent_ACTEN_meeting - growth_status,
  data=train, ntree = 10000)
summary(rf)
rf

varImpPlot(rf)
```


### Classification 

##### Random Forest

```{r}
rf <- randomForest(
  growth_status ~ . -school_code - school_name - percent_ACTWR_meeting - percent_ACTSC_meeting - percent_ACTRD_meeting - percent_ACTMA_meeting - percent_ACTEN_meeting - growth_index_score,
  data=train, ntree = 10000)

pred = predict(rf, newdata=test)
cm = table(test$growth_status, pred)
cm
pred

mean(pred != testing[,16])

varImpPlot(rf)
```